StudioMVC/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudioMVC.Models;
using StudioMVC.StudioDataContext;

namespace StudioMVC.ViewComponents;

public class FooterViewComponent : ViewComponent
{
    public readonly StudioDbContext _context;

    public FooterViewComponent(StudioDbContext context)
    {
        _context = context;
    }
    public async Task<IViewComponentResult> InvokeAsync()
    {
        Dictionary<string, Setting> settings = await _context.Settings.ToDictionaryAsync(s => s.Key);
        return View(settings);
    }
}

StudioMVC/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudioMVC.Models;
using StudioMVC.StudioDataContext;

    public class HeaderViewComponent:ViewComponent
    {
    public readonly StudioDbContext _context;

    public HeaderViewComponent(StudioDbContext context)
    {
        _context = context;
    }
    public async Task<IViewComponentResult> InvokeAsync()
    {
        Dictionary<string, Setting> settings = await _context.Settings.ToDictionaryAsync(s => s.Key);
        return View(settings);
    }
}


StudioMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>Studio</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/boot.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style_common.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style1.css">
    <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300,300italic'>
    <script src="~/assets/js/modernizr.custom.69142.js"></script>
    <script src="~/assets/js/jquery-1.10.1.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
</head>
<body>
    <div id="page-top" class="index">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                @await Component.InvokeAsync("Header")
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="page-scroll" href="#page-top">Home</a></li>
                        <li><a class="page-scroll" href="#services">Services</a></li>
                        <li><a class="page-scroll" href="#port">Portfolio</a></li>
                        <li><a class="page-scroll" href="#about">About</a></li>
                        <li><a class="page-scroll" href="#team">Team</a></li>
                        <li><a class="page-scroll" href="#contact">Contact</a></li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><p class="nav-link scrollto">@User.Identity.Name</p></li>
                            <li>

                                <form method="post" class="nav-link scrollto">
                                    <button asp-controller="Account" asp-action="LogOut" class="btn btn-danger">LogOut</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li><a class="page-scroll" asp-controller="Account" asp-action="Register">Sign Up</a></li>
                            <li><a class="page-scroll" asp-controller="Account" asp-action="LogIn">Log In</a></li>
                        }
                    </ul>
                </div>
            </div><!-- /.container-fluid -->
        </nav>
        <!-- Header -->
        <header style="background-image:url(assets/img/3218_Computer-power-abstract-binary-code.jpg)">
            <div class="container">
                <div class="intro-text">
                    <div class="intro-lead-in">Welcome To Our Studio!</div>
                    <div class="intro-heading">It's Nice To Meet You</div>
                    <a href="#services" class="page-scroll btn btn-primary">Tell Me More</a>
                </div>
            </div>
        </header>
    </div>
        @RenderBody()
        @await Component.InvokeAsync("Footer")
</body>
</html>